jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: gradle build
      - run: cp build/libs/*.jar cts-server-latest.jar
      - setup_remote_docker
      - run:
        name: "create and push docker image"
          environment:
              DOCKER_HUB_ACCT: pratikadhau
              DOCKER_HUB_REPOSITORY: cts-server
              PASSWORD: Password@123
          command: |
              docker build -t $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM .
              docker tag  $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:latest
              docker login -u $DOCKER_HUB_ACCT -p $PASSWORD
              docker push $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM
              docker push $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:latest

